import Link from "next/link";
import { listAdminCategories } from "@/lib/catalog/category-service";

export const dynamic = "force-dynamic";

export default async function AdminProductCategoriesPage() {
  const categories = await listAdminCategories();
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#C8956C]">Catalog</p><h2 className="mt-2 text-3xl font-bold text-[#3D3330]">Product categories</h2><p className="mt-2 text-[#5C534E]">Manage the specification templates used by products, SKUs, and recommendations.</p></div><Link href="/admin/product-categories/new" className="rounded-lg bg-[#C8956C] px-4 py-2 text-sm font-semibold text-white">New category</Link></div><div className="mt-8 overflow-x-auto rounded-xl border border-[#E8DDD4] bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#E8DDD4] text-[#6B6B6B]"><tr><th className="p-4">Category</th><th className="p-4">Role</th><th className="p-4">Recommendation</th><th className="p-4">Status</th><th className="p-4">Products</th><th className="p-4">Template</th></tr></thead><tbody>{categories.map((category: any) => <tr key={category.id} className="border-b border-[#F0E9E4]"><td className="p-4"><Link href={`/admin/product-categories/${category.id}`} className="font-semibold text-[#3D3330] hover:text-[#C8956C]">{category.name}<span className="ml-2 text-xs font-normal text-[#6B6B6B]">{category.slug}</span></Link></td><td className="p-4 text-[#5C534E]">{category.role === "ACCESSORY" ? "Accessory" : "Product"}</td><td className="p-4 text-[#5C534E]">{category.recommendationProfile === "NONE" ? "None" : category.recommendationProfile === "POWERED_WHEELCHAIR" ? "Powered wheelchair" : "Manual wheelchair"}</td><td className="p-4"><span className={category.status === "ACTIVE" ? "text-[#39705E]" : "text-[#8C6D38]"}>{category.status.toLowerCase()}</span></td><td className="p-4 text-[#5C534E]">{category._count?.products ?? 0}</td><td className="p-4 text-[#5C534E]">v{category.templateVersion}</td></tr>)}</tbody></table>{categories.length === 0 && <p className="p-8 text-sm text-[#6B6B6B]">No categories yet.</p>}</div></div>;
}
