"use client";

import { useState } from "react";
import { MediaUploader, type PendingMedia } from "./MediaUploader";

const initial = { name: "", model: "", category: "wheelchair", tagline: "", description: "", price: "", originalPrice: "", amazonLink: "", weightCapacity: "", seatWidth: "", range: "", maxSpeed: "", productWeight: "", features: "", isFeatured: false, sortOrder: "0" };
export function ProductForm() {
  const [form, setForm] = useState(initial); const [images, setImages] = useState<PendingMedia[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const update = (key: keyof typeof initial, value: string | boolean) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(e: React.FormEvent) { e.preventDefault(); setBusy(true); setMessage(""); const payload = { ...form, price: Number(form.price), originalPrice: form.originalPrice ? Number(form.originalPrice) : null, features: form.features.split("\n").map((item) => item.trim()).filter(Boolean), sortOrder: Number(form.sortOrder) }; const body = new FormData(); body.set("payload", JSON.stringify(payload)); images.filter((item) => !item.error).forEach((item) => body.append("images", item.file)); const response = await fetch("/api/admin/products", { method: "POST", body }); const result = await response.json(); setMessage(response.ok ? "Draft saved." : result.error || "Unable to save draft"); setBusy(false); }
  return <form onSubmit={submit} className="max-w-3xl space-y-6"><div className="grid gap-4 sm:grid-cols-2">{([['name','Name'],['model','Model'],['category','Category'],['tagline','Tagline'],['price','Current price'],['originalPrice','Original price'],['amazonLink','Purchase link'],['weightCapacity','Weight capacity'],['seatWidth','Effective seat width'],['range','Range'],['maxSpeed','Max speed'],['productWeight','Product weight'],['sortOrder','Sort order']] as const).map(([key,label]) => <label key={key} className="text-sm font-medium text-[#3D3330]">{label}<input required={key === 'name' || key === 'model' || key === 'price'} type={key.includes('price') || key === 'sortOrder' ? 'number' : key === 'amazonLink' ? 'url' : 'text'} value={form[key]} onChange={(e) => update(key, e.target.value)} className="mt-1 w-full rounded-lg border border-[#D4CCC5] px-3 py-2" /></label>)}</div><label className="block text-sm font-medium text-[#3D3330]">Description<textarea value={form.description} onChange={(e) => update('description', e.target.value)} className="mt-1 min-h-28 w-full rounded-lg border border-[#D4CCC5] px-3 py-2" /></label><label className="block text-sm font-medium text-[#3D3330]">Features, one per line<textarea value={form.features} onChange={(e) => update('features', e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-[#D4CCC5] px-3 py-2" /></label><label className="flex items-center gap-2 text-sm text-[#3D3330]"><input type="checkbox" checked={form.isFeatured} onChange={(e) => update('isFeatured', e.target.checked)} /> Feature on homepage</label><MediaUploader value={images} onChange={setImages} /><div className="flex items-center gap-4"><button disabled={busy || images.some((item) => item.error)} className="rounded-lg bg-[#C8956C] px-5 py-3 font-semibold text-white disabled:opacity-50">{busy ? 'Saving...' : 'Save draft'}</button>{message && <p role="status" className="text-sm text-[#5C534E]">{message}</p>}</div></form>;
}
